[package]
name = "cargo-snippet-more"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
keywords = ["subcommand", "cargo", "snippet", "competitive", "bundler"]
readme = "../README.md"
description= "A fork of cargo-snippet that added bundle and more snippet feature"
categories = ["template-engine"]

[[bin]]
name = "cargo-snippet-more"
path = "src/main.rs"
required-features = ["binaries"]

[dependencies]
cargo-snippet-more-macros.workspace = true
syn = { workspace = true, optional = true }
quote = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }
rustfmt-nightly = { workspace = true, optional = true }
glob = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
log = { workspace = true, optional = true }
env_logger = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
lazy_static = { workspace = true, optional = true }
toml.workspace = true
anyhow.workspace = true
cargo_metadata.workspace = true

[features]
binaries = ["syn", "quote", "proc-macro2", "glob", "clap", "serde", "serde_derive", "serde_json", "log", "env_logger", "regex", "lazy_static"]
inner_rustfmt = ["rustfmt-nightly"]
